### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Zamanry** [rzander/LSARights#1]
Hello, my employer would like to use your code in this repository. Before finding your repository, we had been developing from scratch our own code to duplicate your code's functionality, but then found your code and realized your code was better! We would like to include your code within our own tools, but want to still give credit to you here. Could you add a license so that the usage of your code is documented? Thanks and really appreciate it!

**Comment by rzander** [comment]
This code is freely available here for copying and use. It is not subject to copyright restrictions. It would be appreciated if you could include a link to the original source when sharing your copy.

**Comment by Zamanry** [comment]
Perfect, thank you so much! And will do!
